export const walletActive = [
  {
    label: 'número de póliza',
    field: 'policyNum',
    width: '10em',
    sortable: false,
  },
  {
    label: 'inicio de vigencia',
    field: 'effectiveInitDate',
    width: '10em',
    sortable: false,
  },
  {
    label: 'fin de vigencia',
    field: 'effectiveEndDate',
    width: '10em',
    sortable: false,
  },
  {
    label: 'nombre',
    field: 'name',
    width: '10em',
    sortable: false,
  },
  {
    label: 'apellido',
    field: 'lastName',
    width: '10em',
    sortable: false,
  },
  {
    label: 'fecha de nacimiento',
    field: 'birthday',
    width: '10em',
    sortable: false,
  },
  {
    label: 'rfc',
    field: 'rcf',
    width: '10em',
    sortable: false,
  },
  {
    label: 'dirección',
    field: 'address',
    width: '10em',
    sortable: false,
  },
  {
    label: 'tipo de vivienda',
    field: 'livingPlace',
    width: '10em',
    sortable: false,
  },
  {
    label: 'codigo postal',
    field: 'zipCode',
    width: '10em',
    sortable: false,
  },
  {
    label: 'empresa',
    field: 'company',
    width: '10em',
    sortable: false,
  },
  {
    label: 'colonia',
    field: 'colony',
    width: '10em',
    sortable: false,
  },
  {
    label: 'municipio',
    field: 'municipality',
    width: '10em',
    sortable: false,
  },
  {
    label: 'estado',
    field: 'state',
    width: '10em',
    sortable: false,
  },
  {
    label: 'país',
    field: 'country',
    width: '10em',
    sortable: false,
  },
  {
    label: 'email',
    field: 'email',
    width: '10em',
    sortable: false,
  },
  {
    label: 'teléfono',
    field: 'phone',
    width: '10em',
    sortable: false,
  },
  {
    label: 'monto asegurado',
    field: 'secureAmount',
    width: '10em',
    sortable: false,
  },
  {
    label: 'forma de pago',
    field: 'paymentForm',
    width: '10em',
    sortable: false,
  },
  {
    label: 'prima neta',
    field: 'premium',
    width: '10em',
    sortable: false,
  },
  {
    label: 'derecho de póliza',
    field: 'policyCost',
    width: '10em',
    sortable: false,
  },
  {
    label: 'iva',
    field: 'tax',
    width: '10em',
    sortable: false,
  },
  {
    label: 'total iva',
    field: 'total',
    width: '10em',
    sortable: false,
  },
  {
    label: 'Comision',
    field: 'Commission',
    width: '10em',
    sortable: false,
  },
  {
    label: 'estatus',
    field: 'paymentStatus',
    width: '10em',
    sortable: false,
  },
]

export const labelsAutomarshWalletActive = {
  company: 'EMPRESA',
  policyNum: 'NUMERO DE PÓLIZA',
  effectiveInitDate: 'INICIO DE VIGENCIA',
  effectiveEndDate: 'FIN DE VIGENCIA',
  name: 'NOMBRE',
  lastName: 'APELLIDO',
  birthday: 'FECHA DE NACIMIENTO',
  rcf: 'RFC',
  address: 'DIRECCION',
  zipCode: 'CODIGO POSTAL',
  colony: 'COLONIA',
  municipality: 'MUNICIPIO',
  state: 'ESTADO',
  country: 'PAIS',
  email: 'EMAIL',
  phone: 'TELEFONO',
  livingPlace: 'TIPO DE VIVIENDA',
  secureAmount: 'MONTO ASEGURADO',
  paymentForm: 'FORMA DE PAGO',
  premium: 'PRIMA',
  policyCost: 'DERECHO DE PÓLIZA',
  tax: 'IVA',
  total: 'TOTAL IVA',
  Commission: 'COMISION',
  paymentStatus: 'ESTATUS',
}

export const infoPoliza = [
  {
    label: 'empresa',
    field: 'company',
    width: '10em',
    sortable: false,
  },
  {
    label: 'Número Póliza',
    field: 'policyNum',
    width: '10em',
    sortable: false,
  },
  {
    label: 'Inicio Vigencia',
    field: 'effectiveInitDate',
    width: '10em',
    sortable: false,
  },
  {
    label: 'Fin Vigencia',
    field: 'effectiveEndDate',
    width: '10em',
    sortable: false,
  },
  {
    label: 'nombre',
    field: 'name',
    width: '10em',
    sortable: false,
  },
  {
    label: 'apellido',
    field: 'lastName',
    width: '10em',
    sortable: false,
  },
  {
    label: 'fecha de nacimiento',
    field: 'birthday',
    width: '10em',
    sortable: false,
  },
  {
    label: 'rfc',
    field: 'rcf',
    width: '10em',
    sortable: false,
  },
  {
    label: 'dirección',
    field: 'address',
    width: '10em',
    sortable: false,
  },
  {
    label: 'código postal',
    field: 'zipCode',
    width: '10em',
    sortable: false,
  },
  {
    label: 'colonia',
    field: 'colony',
    width: '10em',
    sortable: false,
  },
  {
    label: 'municipio',
    field: 'municipality',
    width: '10em',
    sortable: false,
  },
  {
    label: 'Estado',
    field: 'state',
    width: '10em',
    sortable: false,
  },
  {
    label: 'país',
    field: 'country',
    width: '10em',
    sortable: false,
  },
  {
    label: 'email',
    field: 'email',
    width: '10em',
    sortable: false,
  },
  {
    label: 'teléfono',
    field: 'phone',
    width: '10em',
    sortable: false,
  },
  {
    label: 'tipo de vivienda',
    field: 'livingPlace',
    width: '10em',
    sortable: false,
  },
  {
    label: 'monto asegurado',
    field: 'secureAmount',
    width: '10em',
    sortable: false,
  },
  {
    label: 'forma de pago',
    field: 'paymentForm',
    width: '10em',
    sortable: false,
  },
  {
    label: 'prima',
    field: 'premium',
    width: '10em',
    sortable: false,
  },
  {
    label: 'derecho de póliza',
    field: 'policyCost',
    width: '10em',
    sortable: false,
  },
  {
    label: 'iva',
    field: 'tax',
    width: '10em',
    sortable: false,
  },
  {
    label: 'total iva',
    field: 'total',
    width: '10em',
    sortable: false,
  },
  {
    label: 'Estatus',
    field: 'status',
    width: '10em',
    sortable: false,
  },
]

export const labelsAutomarshPoliza = {
  company: 'EMPRESA',
  policyNum: 'NUMERO DE PÓLIZA',
  effectiveInitDate: 'INICIO DE VIGENCIA',
  effectiveEndDate: 'FIN DE VIGENCIA',
  name: 'NOMBRE',
  lastName: 'APELLIDO',
  birthday: 'FECHA DE NACIMIENTO',
  rcf: 'RFC',
  address: 'DIRECCION',
  zipCode: 'CODIGO POSTAL',
  colony: 'COLONIA',
  municipality: 'MUNICIPIO',
  state: 'ESTADO',
  country: 'PAIS',
  email: 'EMAIL',
  phone: 'TELEFONO',
  livingPlace: 'TIPO DE VIVIENDA',
  secureAmount: 'MONTO ASEGURADO',
  paymentForm: 'FORMA DE PAGO',
  premium: 'PRIMA',
  policyCost: 'DERECHO DE PÓLIZA',
  tax: 'IVA',
  total: 'TOTAL IVA',
  status: 'ESTATUS',
}

export const infoPayment = [
  {
    label: 'número de póliza',
    field: 'policyNum',
    width: '10em',
    sortable: false,
  },
  {
    label: 'nombre del asegurado',
    field: 'insuredName',
    width: '10em',
    sortable: false,
  },
  {
    label: 'Nombre del Titular de tarjeta',
    field: 'name',
    width: '10em',
    sortable: false,
  },
  {
    label: 'Forma de pago',
    field: 'paymentForm',
    width: '10em',
    sortable: false,
  },
  {
    label: 'Tipo de Pago',
    field: 'paymentType',
    width: '10em',
    sortable: false,
  },
  {
    label: 'Número de autorización',
    field: 'auth',
    width: '10em',
    sortable: false,
  },
  {
    label: 'Número de recibos',
    field: 'invoiceNumber',
    width: '10em',
    sortable: false,
  },
  {
    label: 'Status de pago',
    field: 'paymentStatus',
    width: '10em',
    sortable: false,
  },
  {
    label: 'Fecha de primer pago',
    field: 'firstPaymentDate',
    width: '10em',
    sortable: false,
  },
  {
    label: 'Monto',
    field: 'amount',
    width: '10em',
    sortable: false,
  },
  {
    label: 'Referencia de pago',
    field: 'reference',
    width: '10em',
    sortable: false,
  },
]

export const labelsAutomarshPayments = {
  policyNum: 'NUMERO DE PÓLIZA',
  insuredName: 'NOMBRE DEL ASEGURADO',
  name: 'NOMBRE DEL TITULAR',
  paymentForm: 'FORMA DE PAGO',
  paymentType: 'TIPO DE PAGO',
  auth: 'NUMERO DE AUTORIZACION',
  invoiceNumber: 'NUMERO DE RECIBOS',
  paymentStatus: 'ESTATUS DE PAGO',
  firstPaymentDate: 'FECHA DE PRIMER PAGO',
  amount: 'MONTO',
  reference: 'REFERENCIA DE PAGO',
}
