//esta sera referencia
export const walletActive = [
  {
    label: 'empresa',
    field: 'company',
    width: '10em',
    sortable: false,
  },
  {
    label: 'número póliza',
    field: 'poliza',
    width: '10em',
    sortable: false,
  },
  {
    label: 'inicio vigencia',
    field: 'effectiveDate',
    width: '10em',
    sortable: false,
  },
  {
    label: 'fin vigencia',
    field: 'endEffectiveDate',
    width: '10em',
    sortable: false,
  },
  {
    label: 'nombre',
    field: 'insuredName',
    width: '10em',
    sortable: false,
  },
  {
    label: 'apellido',
    field: 'insuredLastName',
    width: '10em',
    sortable: false,
  },
  {
    label: 'fecha nacimiento',
    field: 'birthday',
    width: '10em',
    sortable: false,
  },
  {
    label: 'rfc',
    field: 'rfc',
    width: '10em',
    sortable: false,
  },
  {
    label: 'dirección',
    field: 'address',
    width: '10em',
    sortable: false,
  },
  {
    label: 'código postal',
    field: 'zipCode',
    width: '10em',
    sortable: false,
  },
  {
    label: 'colonia',
    field: 'suburb',
    width: '10em',
    sortable: false,
  },
  {
    label: 'municipio',
    field: 'municipality',
    width: '10em',
    sortable: false,
  },
  {
    label: 'estado',
    field: 'state',
    width: '10em',
    sortable: false,
  },
  {
    label: 'país',
    field: 'country',
    width: '10em',
    sortable: false,
  },
  {
    label: 'email',
    field: 'email',
    width: '10em',
    sortable: false,
  },
  {
    label: 'teléfono',
    field: 'phone',
    width: '10em',
    sortable: false,
  },
  {
    label: 'tipo vivienda',
    field: 'typeOfHouse',
    width: '10em',
    sortable: false,
  },
  {
    label: 'monto asegurado',
    field: 'secureAmount',
    width: '10em',
    sortable: false,
  },
  {
    label: 'forma pago',
    field: 'paymentFrom',
    width: '10em',
    sortable: false,
  },
  {
    label: 'prima',
    field: 'primaNeta',
    width: '10em',
    sortable: false,
  },
  {
    label: 'derecho poliza',
    field: 'derechoPoliza',
    width: '10em',
    sortable: false,
  },
  {
    label: 'iva',
    field: 'iva',
    width: '10em',
    sortable: false,
  },
  {
    label: 'prima total',
    field: 'total',
    width: '10em',
    sortable: false,
  },
  {
    label: 'estatus',
    field: 'status',
    width: '10em',
    sortable: false,
  },
]

export const labelsWalletActive = {
  company: 'EMPRESA',
  poliza: 'NUMERO DE PÓLIZA',
  effectiveDate: 'INICIO DE VIGENCIA',
  endEffectiveDate: 'FIN DE VIGENCIA',
  insuredName: 'NOMBRE',
  insuredLastName: 'APELLIDO',
  birthday: 'FECHA DE NACIMIENTO',
  rfc: 'RFC',
  address: 'DIRECCIÓN',
  zipCode: 'CODIGO POSTAL',
  suburb: 'COLONIA',
  municipality: 'MUNICIPIO',
  state: 'ESTADO',
  country: 'PAIS',
  email: 'EMAIL',
  phone: 'TELEFONO',
  typeOfHouse: 'TIPO DE VIVIENDA',
  secureAmount: 'MONTO ASEGURADO',
  paymentFrom: 'FORMA DE PAGO',
  primaNeta: 'PRIMA',
  derechoPoliza: 'DERECHO DE POLIZA',
  iva: 'IVA',
  total: 'PRIMA TOTAL',
  status: 'ESTATUS',
}

export const infoPoliza = [
  {
    label: 'empresa',
    field: 'company',
    width: '10em',
    sortable: false,
  },
  {
    label: 'número póliza',
    field: 'poliza',
    width: '10em',
    sortable: false,
  },
  {
    label: 'inicio vigencia',
    field: 'effectiveDate',
    width: '10em',
    sortable: false,
  },
  {
    label: 'fin vigencia',
    field: 'endEffectiveDate',
    width: '10em',
    sortable: false,
  },
  {
    label: 'nombre',
    field: 'insuredName',
    width: '10em',
    sortable: false,
  },
  {
    label: 'apellido',
    field: 'insuredLastName',
    width: '10em',
    sortable: false,
  },
  {
    label: 'fecha nacimiento',
    field: 'birthday',
    width: '10em',
    sortable: false,
  },
  {
    label: 'rfc',
    field: 'rfc',
    width: '10em',
    sortable: false,
  },
  {
    label: 'dirección',
    field: 'address',
    width: '10em',
    sortable: false,
  },
  {
    label: 'codigo postal',
    field: 'zipCode',
    width: '10em',
    sortable: false,
  },
  {
    label: 'colonia',
    field: 'secureAmount',
    width: '10em',
    sortable: false,
  },
  {
    label: 'municipio',
    field: 'suburb',
    width: '10em',
    sortable: false,
  },
  {
    label: 'estado',
    field: 'state',
    width: '10em',
    sortable: false,
  },
  {
    label: 'país',
    field: 'country',
    width: '10em',
    sortable: false,
  },
  {
    label: 'email',
    field: 'email',
    width: '10em',
    sortable: false,
  },
  {
    label: 'teléfono',
    field: 'phone',
    width: '10em',
    sortable: false,
  },
  {
    label: 'tipo vivienda',
    field: 'typeOfHouse',
    width: '10em',
    sortable: false,
  },
  {
    label: 'monto asegurado',
    field: 'secureAmount',
    width: '10em',
    sortable: false,
  },
  {
    label: 'forma pago',
    field: 'paymentFrom',
    width: '10em',
    sortable: false,
  },
  {
    label: 'prima',
    field: 'primaNeta',
    width: '10em',
    sortable: false,
  },
  {
    label: 'derecho poliza',
    field: 'derechoPoliza',
    width: '10em',
    sortable: false,
  },
  {
    label: 'iva',
    field: 'iva',
    width: '10em',
    sortable: false,
  },
  {
    label: 'prima total',
    field: 'total',
    width: '10em',
    sortable: false,
  },
  {
    label: 'estatus',
    field: 'status',
    width: '10em',
    sortable: false,
  },
]

export const labelsPoliza = {
  company: 'EMPRESA',
  poliza: 'NUMERO DE PÓLIZA',
  effectiveDate: 'INICIO DE VIGENCIA',
  endEffectiveDate: 'FIN DE VIGENCIA',
  insuredName: 'NOMBRE',
  insuredLastName: 'APELLIDO',
  birthday: 'FECHA DE NACIMIENTO',
  rfc: 'RFC',
  address: 'DIRECCIÓN',
  zipCode: 'CODIGO POSTAL',
  suburb: 'COLONIA',
  municipality: 'MUNICIPIO',
  state: 'ESTADO',
  country: 'PAIS',
  email: 'EMAIL',
  phone: 'TELEFONO',
  typeOfHouse: 'TIPO DE VIVIENDA',
  secureAmount: 'MONTO ASEGURADO',
  paymentFrom: 'FORMA DE PAGO',
  primaNeta: 'PRIMA',
  derechoPoliza: 'DERECHO DE POLIZA',
  iva: 'IVA',
  total: 'PRIMA TOTAL',
  status: 'ESTATUS',
}

export const infoPayment = [
  {
    label: 'número póliza',
    field: 'policyNum',
    width: '10em',
    sortable: false,
  },
  {
    label: 'nombre asegurado',
    field: 'insuredName',
    width: '10em',
    sortable: false,
  },
  {
    label: 'Nombre Titular',
    field: 'ownerName',
    width: '10em',
    sortable: false,
  },
  {
    label: 'Forma pago',
    field: 'paymentForm',
    width: '10em',
    sortable: false,
  },
  {
    label: 'Tipo Pago',
    field: 'paymentType',
    width: '10em',
    sortable: false,
  },
  {
    label: 'medio pago',
    field: 'paymentMethod',
    width: '10em',
    sortable: false,
  },
  {
    label: 'Número autorizacion',
    field: 'authNumber',
    width: '10em',
    sortable: false,
  },
  {
    label: 'numero recibos',
    field: 'invoiceNumber',
    width: '10em',
    sortable: false,
  },
  {
    label: 'estatus pago',
    field: 'status',
    width: '10em',
    sortable: false,
  },
  {
    label: 'fecha primer pago',
    field: 'createdAt',
    width: '10em',
    sortable: false,
  },
  {
    label: 'monto',
    field: 'amount',
    width: '10em',
    sortable: false,
  },
  {
    label: 'refencia pago',
    field: 'paymentReference',
    width: '10em',
    sortable: false,
  },
]

export const labelsPayments = {
  policyNum: 'NUMERO DE PÓLIZA',
  insuredName: 'NOMBRE DEL ASEGURADO',
  ownerName: 'NOMBRE DEL TITULAR',
  paymentForm: 'FORMA DE PAGO',
  paymentType: 'TIPO DE PAGO',
  paymentMethod: 'MEDIO DE PAGO',
  authNumber: 'NUMERO DE AUTORIZACION',
  invoiceNumber: 'NUMERO DE RECIBOS',
  status: 'ESTATUS DE PAGO',
  createdAt: 'FECHA DE PRIMER PAGO',
  amount: 'MONTO',
  paymentReference: 'REFERENCIA DE PAGO',
}
