//esta sera referencia
export const walletActive = [
  {
    label: 'empresa',
    field: 'company',
    width: '10em',
    sortable: false,
  },
  {
    label: 'número póliza',
    field: 'policyNum',
    width: '10em',
    sortable: false,
  },
  {
    label: 'inicio vigencia',
    field: 'effectiveInitDate',
    width: '10em',
    sortable: false,
  },
  {
    label: 'fin vigencia',
    field: 'effectiveEndDate',
    width: '10em',
    sortable: false,
  },
  {
    label: 'nombre',
    field: 'name',
    width: '10em',
    sortable: false,
  },
  {
    label: 'apellido',
    field: 'lastName',
    width: '10em',
    sortable: false,
  },
  {
    label: 'fecha nacimiento',
    field: 'birthday',
    width: '10em',
    sortable: false,
  },
  {
    label: 'rfc',
    field: 'rcf',
    width: '10em',
    sortable: false,
  },
  {
    label: 'dirección',
    field: 'address',
    width: '10em',
    sortable: false,
  },
  {
    label: 'código postal',
    field: 'zipCode',
    width: '10em',
    sortable: false,
  },
  {
    label: 'colonia',
    field: 'colony',
    width: '10em',
    sortable: false,
  },
  {
    label: 'municipio',
    field: 'municipality',
    width: '10em',
    sortable: false,
  },
  {
    label: 'estado',
    field: 'state',
    width: '10em',
    sortable: false,
  },
  {
    label: 'país',
    field: 'country',
    width: '10em',
    sortable: false,
  },
  {
    label: 'email',
    field: 'email',
    width: '10em',
    sortable: false,
  },
  {
    label: 'teléfono',
    field: 'phone',
    width: '10em',
    sortable: false,
  },
  {
    label: 'tipo vivienda',
    field: 'livingPlace',
    width: '10em',
    sortable: false,
  },
  {
    label: 'monto asegurado',
    field: 'secureAmount',
    width: '10em',
    sortable: false,
  },
  {
    label: 'forma pago',
    field: 'paymentForm',
    width: '10em',
    sortable: false,
  },
  {
    label: 'prima',
    field: 'premium',
    width: '10em',
    sortable: false,
  },
  {
    label: 'derecho poliza',
    field: 'policyCost',
    width: '10em',
    sortable: false,
  },
  {
    label: 'iva',
    field: 'tax',
    width: '10em',
    sortable: false,
  },
  {
    label: 'prima total',
    field: 'total',
    width: '10em',
    sortable: false,
  },
  {
    label: 'estatus',
    field: 'paymentStatus',
    width: '10em',
    sortable: false,
  },
]

export const labelsWalletActiveFed = {
  company: 'EMPRESA',
  policyNum: 'NUMERO DE PÓLIZA',
  effectiveInitDate: 'INICIO DE VIGENCIA',
  effectiveEndDate: 'FIN DE VIGENCIA',
  name: 'NOMBRE',
  lastName: 'APELLIDO',
  birthday: 'FECHA DE NACIMIENTO',
  rcf: 'RFC',
  address: 'DIRECCIÓN',
  zipCode: 'CODIGO POSTAL',
  colony: 'COLONIA',
  municipality: 'MUNICIPIO',
  state: 'ESTADO',
  country: 'PAIS',
  email: 'EMAIL',
  phone: 'TELEFONO',
  livingPlace: 'TIPO DE VIVIENDA',
  secureAmount: 'MONTO ASEGURADO',
  paymentForm: 'FORMA DE PAGO',
  premium: 'PRIMA',
  policyCost: 'DERECHO DE POLIZA',
  tax: 'IVA',
  total: 'PRIMA TOTAL',
  paymentStatus: 'ESTATUS',
}

export const infoPoliza = [
  {
    label: 'empresa',
    field: 'company',
    width: '10em',
    sortable: false,
  },
  {
    label: 'número póliza',
    field: 'policyNum',
    width: '10em',
    sortable: false,
  },
  {
    label: 'inicio vigencia',
    field: 'effectiveInitDate',
    width: '10em',
    sortable: false,
  },
  {
    label: 'fin vigencia',
    field: 'effectiveEndDate',
    width: '10em',
    sortable: false,
  },
  {
    label: 'nombre',
    field: 'name',
    width: '10em',
    sortable: false,
  },
  {
    label: 'apellido',
    field: 'lastName',
    width: '10em',
    sortable: false,
  },
  {
    label: 'fecha nacimiento',
    field: 'birthday',
    width: '10em',
    sortable: false,
  },
  {
    label: 'rfc',
    field: 'rcf',
    width: '10em',
    sortable: false,
  },
  {
    label: 'dirección',
    field: 'address',
    width: '10em',
    sortable: false,
  },
  {
    label: 'codigo postal',
    field: 'zipCode',
    width: '10em',
    sortable: false,
  },
  {
    label: 'colonia',
    field: 'colony',
    width: '10em',
    sortable: false,
  },
  {
    label: 'municipio',
    field: 'municipality',
    width: '10em',
    sortable: false,
  },
  {
    label: 'estado',
    field: 'state',
    width: '10em',
    sortable: false,
  },
  {
    label: 'país',
    field: 'country',
    width: '10em',
    sortable: false,
  },
  {
    label: 'email',
    field: 'email',
    width: '10em',
    sortable: false,
  },
  {
    label: 'teléfono',
    field: 'phone',
    width: '10em',
    sortable: false,
  },
  {
    label: 'tipo vivienda',
    field: 'livingPlace',
    width: '10em',
    sortable: false,
  },
  {
    label: 'monto asegurado',
    field: 'secureAmount',
    width: '10em',
    sortable: false,
  },
  {
    label: 'forma pago',
    field: 'paymentForm',
    width: '10em',
    sortable: false,
  },
  {
    label: 'prima',
    field: 'premium',
    width: '10em',
    sortable: false,
  },
  {
    label: 'derecho poliza',
    field: 'policyCost',
    width: '10em',
    sortable: false,
  },
  {
    label: 'iva',
    field: 'tax',
    width: '10em',
    sortable: false,
  },
  {
    label: 'prima total',
    field: 'total',
    width: '10em',
    sortable: false,
  },
  {
    label: 'estatus',
    field: 'status',
    width: '10em',
    sortable: false,
  },
]

export const labelsPolizaFed = {
  company: 'EMPRESA',
  policyNum: 'NUMERO DE PÓLIZA',
  effectiveInitDate: 'INICIO DE VIGENCIA',
  effectiveEndDate: 'FIN DE VIGENCIA',
  name: 'NOMBRE',
  lastName: 'APELLIDO',
  birthday: 'FECHA DE NACIMIENTO',
  rcf: 'RFC',
  address: 'DIRECCIÓN',
  zipCode: 'CODIGO POSTAL',
  colony: 'COLONIA',
  municipality: 'MUNICIPIO',
  state: 'ESTADO',
  country: 'PAIS',
  email: 'EMAIL',
  phone: 'TELEFONO',
  livingPlace: 'TIPO DE VIVIENDA',
  secureAmount: 'MONTO ASEGURADO',
  paymentForm: 'FORMA DE PAGO',
  premium: 'PRIMA',
  policyCost: 'DERECHO DE POLIZA',
  tax: 'IVA',
  total: 'PRIMA TOTAL',
  status: 'ESTATUS',
}

export const infoPayment = [
  {
    label: 'número póliza',
    field: 'policyNum',
    width: '10em',
    sortable: false,
  },
  {
    label: 'nombre asegurado',
    field: 'insuredName',
    width: '10em',
    sortable: false,
  },
  {
    label: 'Nombre Titular',
    field: 'name',
    width: '10em',
    sortable: false,
  },
  {
    label: 'Forma pago',
    field: 'paymentForm',
    width: '10em',
    sortable: false,
  },
  {
    label: 'Tipo Pago',
    field: 'paymentType',
    width: '10em',
    sortable: false,
  },
  {
    label: 'medio pago',
    field: 'paymentMethod',
    width: '10em',
    sortable: false,
  },
  {
    label: 'Número autorizacion',
    field: 'auth',
    width: '10em',
    sortable: false,
  },
  {
    label: 'numero recibos',
    field: 'invoiceNumber',
    width: '10em',
    sortable: false,
  },
  {
    label: 'estatus pago',
    field: 'paymentStatus',
    width: '10em',
    sortable: false,
  },
  {
    label: 'fecha primer pago',
    field: 'firstPaymentDate',
    width: '10em',
    sortable: false,
  },
  {
    label: 'monto',
    field: 'amount',
    width: '10em',
    sortable: false,
  },
  {
    label: 'refencia pago',
    field: 'reference',
    width: '10em',
    sortable: false,
  },
]

export const labelsPaymentsFed = {
  policyNum: 'NUMERO DE PÓLIZA',
  insuredName: 'NOMBRE DEL ASEGURADO',
  name: 'NOMBRE DEL TITULAR',
  paymentForm: 'FORMA DE PAGO',
  paymentType: 'TIPO DE PAGO',
  paymentMethod: 'MEDIO DE PAGO',
  auth: 'NUMERO DE AUTORIZACION',
  invoiceNumber: 'NUMERO DE RECIBOS',
  paymentStatus: 'ESTATUS DE PAGO',
  firstPaymentDate: 'FECHA DE PRIMER PAGO',
  amount: 'MONTO',
  reference: 'REFERENCIA DE PAGO',
}
